### ISSUE TITLE
Telegram Client Orders confirmation 

### ISSUE THREAD

**Issue by koid38** [diditra/x-ui#11]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

in the "Telegram Client Orders" item in the "Actions" column - the green confirmation button does not work, does not respond to pressing. 
[https://imgur.com/g2p0NOK](url)

and also I want to translate the bot (it's beautiful, I like it very much, thanks for such a bot!) into Russian. How can i do this? I can translate from English into Russian

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by diditra** [comment]
Hi,

You need to have at least 1 inbound before you can confirm a client. After the confirmation the client will be added to the first inbound only. In the future I make it so that it adds to all inbounds.

Regarding the translation create a new file named "crm.ru.json" under the folder translation, copy all the content from crm.en.json to it and translate the values. When you're done you can do a pull request and I'll approve it after testing.

**Comment by koid38** [comment]
Done!

**Comment by koid38** [comment]
I'm sorry, I did this for the first time on Gibhab. Thank you!
