### ISSUE TITLE
Refresh stat as new message in TG bot

### ISSUE THREAD

**Issue by AliM1988** [diditra/x-ui#4]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

HI
In new release v1.0.4 , I see some changes on TG bot, like refreshing stat in-place. I think it is better generate stat as a new message not overwrite. So, the client can check their stat changes.

### Version of x-ui

1.04

### x-ui log or xray log

-

**Comment by diditra** [comment]
I've actually seen that other bots are also doing the same thing. Good thing about not sending a new message every time is that the chat doesn't get crowded. It's specially needed when I add support for multiple accounts per TG ID. When the user chooses Get Usage from the menu, one message per account will be sent, all with update buttons. Otherwise there will be too many messages in the chat (for a multi-account user) and they get confused.
Why do you think it's better to send a new message every time the user presses update?

**Comment by AliM1988** [comment]
One benefit of separated messages is that the clients can see their usages in some days ago and check usage trends. 
Anyway, is there a way for me to return back to v1.0.3 ?

**Comment by diditra** [comment]
You can reinstall any version like this:

bash <(curl -Ls https://raw.githubusercontent.com/diditra/x-ui/master/install.sh) v1.0.3
